name: Vertex
version: '2.0.8'
main: ac.anticheat.vertex.VertexAC
api-version: '1.16'
author: Rukzell
depend: [packetevents]

commands:
  vertex:
    description: Vertex command
    usage: /vertex
    permission: vertex.commands
    aliases: [vac, vertexac]

permissions:
  vertex.alerts:
    default: op
  vertex.reload:
    default: op
  vertex.checks:
    default: op
  vertex.help:
    default: op